# Generated by Django 4.1.11 on 2024-05-25 10:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_id', models.IntegerField()),
                ('lesson', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('type', models.CharField(choices=[('religious', 'Religious'), ('political', 'Political'), ('social', 'Social'), ('protest', 'Protest'), ('government', 'Government'), ('other', 'Other')], default='other', max_length=20)),
                ('attendance', models.IntegerField(default=0)),
                ('stationary', models.BooleanField(default=False)),
                ('start_location', models.CharField(max_length=50)),
                ('end_location', models.CharField(max_length=50)),
                ('police', models.IntegerField(default=0)),
                ('ambulance', models.IntegerField(default=0)),
                ('fire_fighters', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('lesson_learnt', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='gathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('type', models.CharField(choices=[('religious', 'Religious'), ('political', 'Political'), ('social', 'Social'), ('protest', 'Protest'), ('government', 'Government'), ('other', 'Other')], default='other', max_length=20)),
                ('attendance', models.IntegerField(default=0)),
                ('close', models.BooleanField(default=False)),
                ('location', models.TextField()),
                ('police', models.IntegerField(default=0)),
                ('ambulance', models.IntegerField(default=0)),
                ('fire_fighters', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('lesson_learnt', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='epidemic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('type', models.CharField(choices=[('deadly', 'Deadly'), ('seasonal', 'Seasonal'), ('infectious', 'Infectious'), ('other', 'Other')], default='other', max_length=50)),
                ('total_infected', models.IntegerField(default=0)),
                ('cured', models.IntegerField(default=0)),
                ('died', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2020)),
                ('date', models.DateField(blank=True, null=True)),
                ('police', models.IntegerField(default=0)),
                ('hospital_beds', models.IntegerField(default=0)),
                ('health_staff', models.IntegerField(default=0)),
                ('lesson_learnt', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('type', models.CharField(choices=[('murder', 'Murder'), ('rape', 'Rape'), ('kidnapping', 'Kidnapping'), ('loot', 'Loot'), ('robbery', 'Robbery'), ('smuggling', 'Smuggling'), ('other', 'Other')], default='other', max_length=20)),
                ('crime_location', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('lesson_learnt', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='calamity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('type', models.CharField(choices=[('floods', 'Floods'), ('drought', 'Drought'), ('earthquake', 'Earthquake'), ('forest fire', 'Forestfire'), ('cyclone', 'Cyclone'), ('landslide', 'Landslide'), ('storm', 'Storm'), ('other', 'Other')], default='other', max_length=20)),
                ('total_cost', models.BigIntegerField(default=0)),
                ('injured', models.IntegerField(default=0)),
                ('dead', models.IntegerField(default=0)),
                ('people_affected', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('police', models.IntegerField(default=0)),
                ('ambulance', models.IntegerField(default=0)),
                ('ndrf', models.IntegerField(default=0)),
                ('lesson_learnt', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
