# Generated by Django 4.1.11 on 2024-05-25 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compliance',
            fields=[
                ('is_meeting_related', models.BooleanField()),
                ('compliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
                ('deadline', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('reminder_period', models.DurationField(default=datetime.timedelta(days=7))),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(to='common.message')),
                ('related_document', models.ManyToManyField(to='common.document')),
                ('related_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.meeting')),
                ('related_users', models.ManyToManyField(related_name='related_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
