# Generated by Django 4.1.11 on 2024-05-25 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('area', models.IntegerField(blank=True)),
                ('state', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('population', models.PositiveIntegerField(default=0)),
                ('district', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('meeting', 'Meeting'), ('compliance', 'Compliance'), ('message', 'Message')], max_length=10)),
                ('document_link', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=8, null=True)),
                ('document_name', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=7)),
                ('dob', models.DateField(blank=True)),
                ('batch', models.PositiveSmallIntegerField(blank=True)),
                ('district', models.CharField(blank=True, max_length=30)),
                ('image', models.CharField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=12)),
                ('departments', models.ManyToManyField(to='common.department')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('message_text', models.CharField(max_length=200)),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_by', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to=settings.AUTH_USER_MODEL)),
                ('related_documents', models.ManyToManyField(to='common.document')),
            ],
        ),
    ]
